elifeLibrary {
    stage 'Checkout', {
        checkout scm
    }

    stage 'Project tests', {
        elifeLocalTests "./project_tests.sh"
        echo 'Checking changes have not been generated by the style checker. If this fails, run .lint.sh from your the venv/ virtualenv'
        sh 'git diff --exit-code'
    }
    
    elifeMainlineOnly {    
        stage 'Master', {
            elifeGitMoveToBranch elifeGitRevision(), 'master'
        }
    }
}
