elifeLibrary({
    stage 'Checkout', {
        checkout scm
    }

    stage 'Project tests', {
        elifeLocalTests "./project_tests.sh"
        echo 'Checking changes have not been generated by the style checker. If this fails, run .lint.sh from your the venv/ virtualenv'
        sh 'git diff --exit-code'
    }

    stage 'Guinea pigs', {
        sh './download-elife-xml.sh'
        sh './guinea-pigs.sh'
    }

    stage 'Corpus generation', {
        sh 'rm -f generation.log'
        sh './generate-article-json.sh'
        archive 'generation.log'
        sh './generate-statistics.sh generation.log'
    }

    stage 'Corpus validation', {
        sh './validate-all-json.sh'
    }

    elifeMainlineOnly {    
        stage 'Master', {
            elifeGithubCommitStatus elifeGitRevision(), 'success', 'continuous-integration/jenkins/pr-head', 'Alfred automated merge to master'
            elifeGitMoveToBranch elifeGitRevision(), 'master'
        }

        stage 'Downstream', {
            build job: '/dependencies/dependencies-lax-update-bot-lax-adaptor', wait: false
        }
    }

}, 'elife-libraries--powerful3', 600)
